### ISSUE TITLE
Add section about camera

### ISSUE THREAD

**Issue by lucasdemarchi** [intel-aero/intel-aero-docs#11]
https://intel-aero.github.io/getting-started/camera/

Should give pointers on how to stream Realsense on current release, possibly mentioning improves for the next ones. Wrong info from wiki to be used with care: https://github.com/intel-aero/meta-intel-aero/wiki/02-Initial-setup#video-streaming-using-qgroundcontrol

**Comment by anselmolsm** [comment]
ping @zehortigoza

**Comment by zehortigoza** [comment]
https://github.com/intel-aero/intel-aero-docs/pull/31
