### ISSUE TITLE
Populate mods section or reorganize to feature content currently at instructables.com

### ISSUE THREAD

**Issue by anselmolsm** [intel-aero/intel-aero-docs#3]
There's interesting content about Intel Aero published at instructables.com. The idea is to add a gallery, a link or something that creates a links between the dev docs and such content.

The 'mods' sections mentioned is https://intel-aero.github.io/hw/mods/

**Comment by lfelipe** [comment]
@broody can you take a stab at this?

**Comment by broody** [comment]
Roger wilco
