### ISSUE TITLE
Development/Flight Stacks

### ISSUE THREAD

**Issue by anselmolsm** [intel-aero/intel-aero-docs#38]
https://intel-aero.github.io/dev/flight-stacks/

A guide for developers who want to develop the flight stacks:
 - link to the upstream projects
 - instructions on how to build and flash a custom firmware version:
    - PX4: make aerofc-v1 upload
    - ArduPilot: ./waf configure --board aerofc-v1 && ./waf --target bin/arducopter --upload

**Comment by avinash-palleti** [comment]
@lucasdemarchi @anselmolsm Please review the commit once,
https://github.com/avinash-palleti/intel-aero-docs/commit/864b8a38c72b7e5f7222ff41cacfdbddf79f2d8b

Let me know if anything needs to be added, otherwise i will submit PR.

**Comment by lucasdemarchi** [comment]
Can you send it as PR?

**Comment by avinash-palleti** [comment]
https://github.com/intel-aero/intel-aero-docs/pull/44
