### ISSUE TITLE
Add information about flight stack logs

### ISSUE THREAD

**Issue by zehortigoza** [intel-aero/intel-aero-docs#4]
This information is also missing in our wiki.

**Comment by sugnanprabhu** [comment]
@zehortigoza Please check PR #28 , please suggest if we can add any more information to this page.
I have not included the instructions for retrieving the logs using cockpit (https://github.com/intel-aero/aero-cockpit-plugins/pull/6) as it is not part of the current release.

**Comment by zehortigoza** [comment]
Looks nice Sugnan, thanks
